### ISSUE TITLE
Automated build on Docker Hub

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/jupyterlab-experiment-builder#14]
The Docker image should be available on Docker Hub and be build there.

**Comment by sverhoeven** [comment]
@nielsdrost can you give me permission on https://hub.docker.com/u/ewatercycle/?

**Comment by nielsdrost** [comment]
Done. Sorry it took a while.

**Comment by sverhoeven** [comment]
Thanks, automated build has been setup https://hub.docker.com/r/ewatercycle/jupyterlab-experiment-builder/.
Waiting for build to finish to add badges.
